/**
 * Static analysis of an installed supervisor service definition.
 *
 * Pure by contract: file text in, findings out. It runs no subprocess and reads no disk,
 * so it is assertable against known-bad fixtures — a Homebrew-shaped unit with no
 * `KillMode`, a root-run unit, a data root that disagrees with the caller's.
 *
 * The `unverifiable` severity is load-bearing. Anything this analyser cannot see from the
 * file alone (is the unit actually running, is lingering enabled) must be reported as
 * unverified rather than as a negative: a failed probe is not evidence of a stopped
 * service, and guessing is the failure mode `ssh-execution-boundary.md` forbids.
 */
import {
  DISCOURAGED_SYSTEMD_KILL_MODES,
  SAFE_SYSTEMD_KILL_MODES,
  type SupervisorPlatform,
  type SupervisorScope
} from './supervisor-service-render'

export type SupervisorFindingSeverity = 'critical' | 'warning' | 'unverifiable' | 'ok'

export type SupervisorFinding = {
  code: string
  severity: SupervisorFindingSeverity
  message: string
  /** Shown verbatim to an operator; omitted when there is nothing to run. */
  remedy?: string
}

export type SupervisorServiceFile = {
  path: string
  text: string
  platform: SupervisorPlatform
  scope: SupervisorScope
}

export type SupervisorAuditInput = {
  /** Every definition found, not just the first — two contending for one data root is the finding. */
  files: SupervisorServiceFile[]
  /** What the calling shell resolves, to compare against what the file pins. */
  expectedUserDataPath: string
}

/** systemd `Key=value`, ignoring comments. Last assignment wins, as systemd itself does. */
function readSystemdKey(text: string, key: string): string | null {
  let found: string | null = null
  for (const raw of text.split('\n')) {
    const line = raw.trim()
    if (line.startsWith('#') || line.startsWith(';')) {
      continue
    }
    const match = new RegExp(`^${key}\\s*=\\s*(.*)$`).exec(line)
    if (match) {
      found = match[1].trim()
    }
  }
  return found
}

/**
 * `<key>Name</key>` followed by its value element. Deliberately not an XML parser: the
 * audit must work on a hand-edited plist that a strict parser would reject outright.
 */
function readPlistBoolean(text: string, key: string): boolean | null {
  const match = new RegExp(`<key>\\s*${key}\\s*</key>\\s*<(true|false)\\s*/>`, 'i').exec(text)
  return match ? match[1].toLowerCase() === 'true' : null
}

function readPlistString(text: string, key: string): string | null {
  const match = new RegExp(`<key>\\s*${key}\\s*</key>\\s*<string>([^<]*)</string>`, 'i').exec(text)
  return match ? match[1].trim() : null
}

/** systemd writes `Environment=NAME=value`; the plist nests it under EnvironmentVariables. */
function readPinnedUserData(file: SupervisorServiceFile): string | null {
  if (file.platform === 'systemd') {
    for (const raw of file.text.split('\n')) {
      const line = raw.trim()
      if (line.startsWith('#')) {
        continue
      }
      const match = /^Environment\s*=\s*"?ORCA_USER_DATA=([^"]*)"?$/.exec(line)
      if (match) {
        return match[1].trim()
      }
    }
    return null
  }
  const dict = /<key>\s*EnvironmentVariables\s*<\/key>\s*<dict>([\s\S]*?)<\/dict>/i.exec(file.text)
  return dict ? readPlistString(dict[1], 'ORCA_USER_DATA') : null
}

/**
 * The check the whole feature exists for. A missing `KillMode` is not a neutral omission:
 * systemd's default is `control-group`, which reaps the detached terminal daemon and turns
 * every restart into lost work. That is precisely what `brew services` generates.
 */
function auditKillSemantics(file: SupervisorServiceFile): SupervisorFinding {
  if (file.platform === 'launchd') {
    const abandon = readPlistBoolean(file.text, 'AbandonProcessGroup')
    if (abandon === true) {
      return {
        code: 'kill_semantics_safe',
        severity: 'ok',
        message: 'AbandonProcessGroup is true: launchd will not reap the terminal daemon.'
      }
    }
    return {
      code: 'kill_semantics_implicit',
      severity: 'warning',
      message:
        'AbandonProcessGroup is not set. Terminals survive today only because the daemon ' +
        'setsid()s out of the job process group — an implementation detail, not a guarantee.',
      remedy: 'Regenerate with: orcad --print-service'
    }
  }
  const killMode = readSystemdKey(file.text, 'KillMode')
  if (killMode === null) {
    return {
      code: 'kill_mode_missing',
      severity: 'critical',
      message:
        'No KillMode, so systemd applies control-group and kills the detached terminal ' +
        'daemon with the runtime. Every restart destroys running terminals. A unit ' +
        'generated by `brew services` looks exactly like this.',
      remedy: 'Regenerate with: orcad --print-service'
    }
  }
  if (!SAFE_SYSTEMD_KILL_MODES.includes(killMode as (typeof SAFE_SYSTEMD_KILL_MODES)[number])) {
    return {
      code: 'kill_mode_reaps_group',
      severity: 'critical',
      message: `KillMode=${killMode} reaps the whole control group, including the detached terminal daemon.`,
      remedy: 'Set KillMode=mixed'
    }
  }
  if (
    DISCOURAGED_SYSTEMD_KILL_MODES.includes(
      killMode as (typeof DISCOURAGED_SYSTEMD_KILL_MODES)[number]
    )
  ) {
    return {
      code: 'kill_mode_discouraged',
      severity: 'warning',
      message: `KillMode=${killMode} spares the daemon but signals nothing at all, so orcad never gets its graceful stop and systemd deprecates it.`,
      remedy: 'Set KillMode=mixed'
    }
  }
  return {
    code: 'kill_semantics_safe',
    severity: 'ok',
    message: `KillMode=${killMode}: the terminal daemon survives a runtime restart.`
  }
}

function auditUserDataPath(file: SupervisorServiceFile, expected: string): SupervisorFinding {
  const pinned = readPinnedUserData(file)
  if (pinned === null) {
    return {
      code: 'user_data_unpinned',
      severity: 'critical',
      message:
        'No ORCA_USER_DATA. A service inherits almost no environment, so it resolves its ' +
        'own data root — which can differ from the one your shell resolves. The service ' +
        'then starts healthy and shows none of your repositories.',
      remedy: `Add the resolved root explicitly: ${expected}`
    }
  }
  if (pinned !== expected) {
    return {
      code: 'user_data_mismatch',
      severity: 'warning',
      message: `Service uses ${pinned}; this shell resolves ${expected}. Deliberate for a dedicated service account, a split profile otherwise.`
    }
  }
  return { code: 'user_data_agrees', severity: 'ok', message: `Data root pinned to ${pinned}.` }
}

function auditRunAsUser(file: SupervisorServiceFile): SupervisorFinding {
  const user =
    file.platform === 'systemd'
      ? readSystemdKey(file.text, 'User')
      : readPlistString(file.text, 'UserName')
  if (user === null) {
    return {
      code: 'run_as_user_unset',
      severity: file.scope === 'system' ? 'critical' : 'ok',
      message:
        file.scope === 'system'
          ? 'No run-as account on a system service, so orcad runs as root and creates a ' +
            'root-owned data root. Every later run as a normal user then fails with ' +
            'orcad_data_root_wrong_owner, which orcad will not repair.'
          : 'No run-as account, which is correct for a user-scope service.',
      remedy: file.scope === 'system' ? 'Add an explicit run-as account.' : undefined
    }
  }
  if (user === 'root') {
    return {
      code: 'run_as_root',
      severity: 'critical',
      message:
        'Service runs orcad as root, which creates a root-owned data root no later user run can use.',
      remedy: 'Set the account orcad should run as.'
    }
  }
  return { code: 'run_as_user_set', severity: 'ok', message: `Runs as ${user}.` }
}

/**
 * A user-scope service dies with the session that installed it — the exact failure this
 * whole feature prevents. Whether lingering is on cannot be read from the file, so this
 * reports `unverifiable` rather than pretending either way.
 */
function auditSurvivesLogout(file: SupervisorServiceFile): SupervisorFinding | null {
  if (file.scope === 'system') {
    return null
  }
  return file.platform === 'systemd'
    ? {
        code: 'linger_unverified',
        severity: 'unverifiable',
        message:
          'User-scope unit: it stops when your last session ends unless lingering is enabled. ' +
          'Not readable from the unit file.',
        remedy:
          'loginctl show-user "$USER" --property=Linger  # then: sudo loginctl enable-linger "$USER"'
      }
    : {
        code: 'launch_agent_scope',
        severity: 'warning',
        message:
          'LaunchAgent: runs only while this user is logged in, so a headless Mac loses the ' +
          'service at logout.',
        remedy: 'Regenerate with --scope system to get a LaunchDaemon.'
      }
}

/** Both formats can be syntactically fine and still name nothing to run. */
function auditExecTarget(file: SupervisorServiceFile): SupervisorFinding | null {
  const hasTarget =
    file.platform === 'systemd'
      ? readSystemdKey(file.text, 'ExecStart') !== null
      : /<key>\s*ProgramArguments\s*<\/key>\s*<array>\s*<string>/i.test(file.text)
  return hasTarget
    ? null
    : {
        code: 'exec_target_missing',
        severity: 'critical',
        message:
          file.platform === 'systemd'
            ? 'No ExecStart: this unit cannot start anything.'
            : 'No ProgramArguments: this job cannot start anything.'
      }
}

/**
 * Ranked first when it fires, because it explains failures every other check would
 * misattribute: the second service to start hits orcad's instance lock, exits 78, and
 * `RestartPreventExitStatus=78` leaves it permanently failed. The visible symptom is a
 * service that will not start; the cause is a different one that already won.
 */
function auditDuplicates(input: SupervisorAuditInput): SupervisorFinding | null {
  if (input.files.length < 2) {
    return null
  }
  const roots = new Map<string, string[]>()
  for (const file of input.files) {
    const root = readPinnedUserData(file) ?? input.expectedUserDataPath
    roots.set(root, [...(roots.get(root) ?? []), file.path])
  }
  const contended = [...roots.entries()].filter(([, paths]) => paths.length > 1)
  if (contended.length === 0) {
    return {
      code: 'multiple_services_distinct_roots',
      severity: 'warning',
      message: `${input.files.length} orcad services found, each with its own data root: ${input.files.map((f) => f.path).join(', ')}`
    }
  }
  return {
    code: 'multiple_services_one_root',
    severity: 'critical',
    message:
      `More than one orcad service targets the same data root — ${contended
        .map(([root, paths]) => `${root}: ${paths.join(' and ')}`)
        .join('; ')}. Only one can hold the instance lock; the other exits 78 and stays ` +
      'permanently failed, so its start failure is caused by the service that already won.',
    remedy: 'Remove the service you did not intend to keep, then: systemctl reset-failed'
  }
}

export function auditSupervisorServices(input: SupervisorAuditInput): SupervisorFinding[] {
  if (input.files.length === 0) {
    return [
      {
        code: 'no_service_found',
        severity: 'unverifiable',
        message: 'No orcad service definition found in the conventional locations.',
        remedy: 'orcad --print-service'
      }
    ]
  }
  const findings: SupervisorFinding[] = []
  const duplicates = auditDuplicates(input)
  if (duplicates) {
    findings.push(duplicates)
  }
  for (const file of input.files) {
    findings.push(auditKillSemantics(file))
    findings.push(auditUserDataPath(file, input.expectedUserDataPath))
    findings.push(auditRunAsUser(file))
    const logout = auditSurvivesLogout(file)
    if (logout) {
      findings.push(logout)
    }
    const exec = auditExecTarget(file)
    if (exec) {
      findings.push(exec)
    }
  }
  const rank: Record<SupervisorFindingSeverity, number> = {
    critical: 0,
    warning: 1,
    unverifiable: 2,
    ok: 3
  }
  return findings.sort((a, b) => rank[a.severity] - rank[b.severity])
}

/** True when nothing found would lose an operator's running terminals. */
export function supervisorAuditPassed(findings: SupervisorFinding[]): boolean {
  return !findings.some((finding) => finding.severity === 'critical')
}
